### ISSUE TITLE
Repeated flags working as intended?

### ISSUE THREAD

**Issue by HarveyEllis** [deislabs/porter-aws#15]
## Describe the bug
When using the aws mixin multiple flags don't seem to work correctly. The action I am trying to perform is create an ec2 instance with multiple security groups. This could be related to #11 ?

## To Reproduce

There are several scenarios here:
### 1. Multiple items added as a YAML sequence
```
install:
  - aws:
      description: "Provision VM"
      service: ec2
      operation: run-instances
      flags:
        image-id: ami-xxxxxxxxxxxxxxxxx
        instance-type: t2.micro
        region: eu-west-1
        subnet-id: subnet-xxxxxx
        security-group-ids: 
        - sg-xxxxxxxx
        - sg-xxxxxxxx
```

### 2. Multiple items added as a formatted string
Replace the SG sequence with:
```
security-group-ids: "\"sg-xxxxxxxx\" \"sg-xxxxxxxx\""
```

### 3. Multiple items added as a 'simple' string
Replace the SG sequence with:
```
security-group-ids: "sg-xxxxxxxx sg-xxxxxxxx"
```

## Expected behavior
That you can add multiple items, for instance multiple SGs to a yaml config and have them all attach. Some of the above options produce the correct output in the debug console (running install with the `--debug` flag) but the commands don't seem to work.

## Porter Command and Output
```
porter install --cred aws_nonprod_creds --debug
```
For the different scenarios: 
### 1. Multiple items added as a YAML sequence:
This adds multiple `--security-group-ids` to the `aws ec2` command:
```
aws ec2 run-instances --image-id ami-xxxxxxxxxxxxxxxxx --instance-type t2.micro --output json --region eu-west-1 --security-group-ids sg-xxxxxxxx --security-group-ids sg-xxxxxxxx --subnet-id subnet-xxxxxxxx
```
Only the last is chosen and applied - I think this is in the AWS docs somewhere, but can't remember where (sorry!)

### 2. Multiple items added as a formatted string
This would seem to produce a correctly formatted output (i.e. if you run something like this outside of porter then it will run and create you an instance as intended)
```
aws ec2 run-instances --image-id ami-xxxxxxxxxxxxxxxxx --instance-type t2.micro --output json --region eu-west-1 --security-group-ids "sg-xxxxxxxx" "sg-xxxxxxxx" --subnet-id subnet-xxxxxxxx
```
But the error that you get is: `The parameter groupName cannot be used with the parameter subnet`. To me this implies it is trying to do something with the default subnet or an SG that is not in the same subnet - however, I have checked on my example and it works outside of the bundle so this is not the case.

### 3. Multiple items added as a 'simple' string
This would also seem to produce a correctly formatted output - same as no.2 just without quotes around the SGs:
```
aws ec2 run-instances --image-id ami-xxxxxxxxxxxxxxxxx --instance-type t2.micro --output json --region eu-west-1 --security-group-ids sg-xxxxxxxx sg-xxxxxxxx --subnet-id subnet-xxxxxxxx
```

The error is the same as for no.2: `The parameter groupName cannot be used with the parameter subnet`

## Version
porter v0.23.0-beta.1 (9c49056)
aws v0.2.1-beta.1 (can't seem to find version hash)
